using System;
using System.IO;
using System.Drawing;

/*
 * Vizzi is a tool that can take ram.dat files that are generated by Benjojo's fork of bochs
 * and then make a collection of frames that can then be compiled (by using a tool like ffmpeg)
 * into a nice little film showing you where the RAM was being written to during the OS's boot.
 */

namespace vizzi
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("Vizzi is a tool that can vizualize ram.dat files that are generated by Benjojo's fork of bochs");#
                Console.WriteLine("To use please input a ram.dat file.");
                Console.WriteLine("$ mono vizzi.exe ram.dat");
                Environment.Exit(0);
            }
            else 
            {
                if(File.Exists(args[0]))
                {

                }
                else
                {
                    Console.WriteLine("That file seems to not exist. Exiting.");
                    Environment.Exit(1);
                }
            }
        }
    }
}
